# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knn_index_dist_rcpp <- function(MATRIX, TEST_DATA, k, method, threads, eps = 1.0e-6) {
    .Call('KernelKnn_knn_index_dist_rcpp', PACKAGE = 'KernelKnn', MATRIX, TEST_DATA, k, method, threads, eps)
}

